name: he
description: "A simple UI library for Flutter."
version: 0.0.2+1
homepage: https://github.com/guchengxi1994/he

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  polygon: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


